# Generated by Django 4.0.5 on 2024-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_alter_host_asset_no_alter_host_cpu_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_passwd',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='操作系统的密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='os_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统用户'),
        ),
    ]
